# Generated by Django 4.1.3 on 2022-11-07 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 18, 9, 28, 177985)),
        ),
    ]
