# Generated by Django 4.1.3 on 2022-11-21 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_customuser_login_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ids', models.IntegerField(default=None)),
                ('website_name', models.CharField(max_length=200)),
                ('website_host', models.CharField(max_length=200)),
                ('website_ip', models.CharField(max_length=200)),
                ('website_username', models.CharField(max_length=50)),
                ('website_password', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 21, 10, 57, 21, 766877)),
        ),
    ]
